### ISSUE TITLE
Keine Anzeige im magicmirror 

### ISSUE THREAD

**Issue by hilope** [fuerst/MMM-MensaMax#1]
Hallo,

ich habe alles installiert nach Anweisung , gab teilweise Probleme mit den npm-Modulen, die ich aber alle nachinstalliert habe. Anfangs gab es nämlich Fehlermeldungen wegen fehlender Module .
Jetzt kommen keine Fehler mehr, aber auch keinerlei Daten auf dem mirror.
Kann es damit zusammenhängen, das das Modul nur das Projekt benutzt für den Login? Auf der Website gibt es ja noch zusätzlich die Einrichtung.

Würde mich freuen, wenn ich das noch zum laufen bekomme :)

**Comment by fuerst** [comment]
MMM-MensaMax nutzt die selbe Schnittstelle, die auch von der offiziellen MensaMax-App verwendet wird. Dort ist die Eingabe der Einrichtung nicht vorgesehen. Testen kannst Du das hier: https://m.mensamax.de. Funktioniert Dein Login auf dieser Webseite?

Ansonsten müsstest Du einmal nach Fehlermeldungen im Log von MagicMirror suchen, die in Zusammenhang mit MensaMax stehen.

**Comment by hilope** [comment]
Danke für die schnelle Antwort.
Wenn es an den Zugangsdaten liegt, müsste doch wenigsten der Titel des Moduls oder so angezeigt werden, oder nicht? Die Daten sind jedenfalls korrekt.

Wenn ich "pm2 logs" starte und die Seite neu lade bekomme ich folgende Meldung:

`[23.12.2022 08:15.25.390] [ERROR] FetchError: maximum redirect reached at: https://m.mensamax.de/graphql/auth/login
0|mm  |     at ClientRequest.<anonymous> (/home/hilope/MagicMirror/modules/MMM-MensaMax/node_modules/node-fetch/lib/index.js:1546:15)
0|mm  |     at ClientRequest.emit (node:events:526:28)
0|mm  |     at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
0|mm  |     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
0|mm  |     at TLSSocket.socketOnData (node:_http_client:482:22)
0|mm  |     at TLSSocket.emit (node:events:526:28)
0|mm  |     at addChunk (node:internal/streams/readable:315:12)
0|mm  |     at readableAddChunk (node:internal/streams/readable:289:9)
0|mm  |     at Readable.push (node:internal/streams/readable:228:10)
0|mm  |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
0|mm  |   type: 'max-redirect'
0|mm  | }`

Was bedeutet das?

**Comment by fuerst** [comment]
Ich habe jetzt einen Text _Warte auf Daten..._ hinzugefügt, der angezeigt wird, wenn noch keine Daten von MensaMax zurückgegeben wurden. Im Fehlerfall bleibt der Text stehen. Dann musst Du das Log prüfen.

Der oben genannte Error taucht auf, wenn MensaMax einen Cookie namens _mensamax_superglue_ nicht oder mit falschen Werten erhält. Kannst Du Dich einmal an der MensaMax-Seite anmelden, die Du üblicherweise für die Verwaltung des Speiseplans verwendest. Anschließend schaust Du nach, welchen Inhalt (Wert) dieser Cookie hat. Im Chrome-Browser geht das per Klick auf das Schloss-Icon neben der Webadresse, dann weiter mit Klick auf _Cookies_, _login.mensaweb.de_ (oder ähnlich), dann wieder _Cookies_, dann _mensamax_superglue_

Bei mir hat der Cookie den Wert _https://login.mensaweb.de_. Wie ist das bei Dir?

**Comment by hilope** [comment]
Ah, da habe ich "https://mensadigital.de" - also einen ganz anderen Wert. Egal über welche Login-Seite ich gehe, jedes Mal lande ich bei mensadigital.de 

Vielleicht haben unterschiedliche Einrichtungen auch unterschiedliche Domains zur Verwaltung ^^

**Comment by fuerst** [comment]
Ja, das hängt anscheinend von der Einrichtung bzw. dem Projekt ab.
Versuch es einmal mit der aktuellen Version. Die liest den _mensamax_superglue_ aus der Antwort des Servers aus - damit funktioniert es jetzt hoffentlich für jede Einrichtung / Projekt.

**Comment by hilope** [comment]
Danke. Jetzt geht es!
Jetzt sehe ich auch die bestellten Gerichte., Guthaben usw. Vielen Dank nochmal.
